{{- if eq .Values.daemonset.enabled true -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nrotel.daemonsetName" . }}
  {{- if .Values.daemonset.clusterRole.annotations }}
  annotations:
    {{- range $key, $value := .Values.daemonset.clusterRole.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
rules:
  {{- if .Values.daemonset.clusterRole.rules -}}
  {{ toYaml .Values.daemonset.clusterRole.rules | nindent 2 -}}
  {{- end }}
{{- end -}}
