{{- if eq .Values.deployment.enabled true -}}
{{- $teams := include "deploymentTeamConfig" . | fromYaml }}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "nrotel.deploymentNameReceiver" . }}
  namespace: {{ .Release.Namespace }}
spec:

  # Mode
  mode: "deployment"

  # Service Account
  serviceAccount: {{ include "nrotel.deploymentName" . }}

  # Security context for container priviliges
  {{- with .Values.deployment.securityContext }}
  securityContext: {{ toYaml . | nindent 4 }}
  {{- end }}

  # Annotations for the pods
  podAnnotations:
    prometheus.io/scrape: "false" # This should be false by default. Otherwise 'otelcollector' self scraper job AND 'kubernetes-pods' scrape job will both scrape
  {{- range $key, $val := .Values.deployment.annotations }}
    {{ $key }}: {{ $val }}
  {{- end }}

  # Ports to expose per service
  ports:
    - name: prometheus
      protocol: TCP
      port: {{ .Values.deployment.ports.prometheus.port }}
      targetPort: {{ .Values.deployment.ports.prometheus.targetPort }}

  # Image
  image: "{{ .Values.deployment.image.repository }}:{{ include "nrotel.deploymentImageTag" . }}"
  imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}

  # Resources
  resources:
    requests:
      cpu: {{ .Values.deployment.resources.requests.cpu }}
      memory: {{ .Values.deployment.resources.requests.memory }}
    limits:
      cpu: {{ .Values.deployment.resources.limits.cpu }}
      memory: {{ .Values.deployment.resources.limits.memory }}

  # Replicas
  replicas: {{ .Values.deployment.replicas.receiver }}

   # Autoscaling configuration
  {{- if eq .Values.deployment.autoscaler.receiver.enabled true }}
  autoscaler:
    minReplicas: {{ .Values.deployment.autoscaler.receiver.minReplicas }}
    maxReplicas: {{ .Values.deployment.autoscaler.receiver.maxReplicas }}
    targetCPUUtilization: {{ .Values.deployment.autoscaler.receiver.targetCPUUtilization }}
    targetMemoryUtilization: {{ .Values.deployment.autoscaler.receiver.targetMemoryUtilization }}
  {{- end }}

  # Environment variables
  env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    {{- range $teamName, $teamInfo := $teams }}
      {{- if ne $teamInfo.ignore true }}
    - name: {{ $teamName }}_endpoint
      value: {{ $teamInfo.endpoint }}
        {{- if $teamInfo.licenseKey.secretRef }}
    - name: {{ $teamName }}_licenseKey
      valueFrom:
        secretKeyRef:
          name: {{ $teamInfo.licenseKey.secretRef.name }}
          key: {{ $teamInfo.licenseKey.secretRef.key }}
        {{- else if $teamInfo.licenseKey.value }}
    - name: {{ $teamName }}_licenseKey
      valueFrom:
        secretKeyRef:
          name: {{ include "nrotel.deploymentName" $ }}-{{ $teamName }}
          key: licenseKey
        {{- end }}
      {{- end }}
    {{- end }}

  # Otel configuration
  config:
    receivers:
      prometheus/self:
        config:
          scrape_configs:
            - job_name: 'otelcollector'
              scrape_interval: {{ .Values.deployment.prometheus.receiver.self.scrapeInterval }}
              static_configs:
              - targets:
                - 127.0.0.1:{{ .Values.deployment.ports.prometheus.port }}
              {{- if ne (len .Values.deployment.prometheus.receiver.self.importantMetrics) 0 }}
                {{ $metrics := "" -}}
                {{- range $index, $metric := .Values.deployment.prometheus.receiver.self.importantMetrics -}}
                  {{- if eq $index 0 -}}
                    {{- $metrics = printf "%s" $metric -}}
                  {{ else }}
                    {{- $metrics = printf "%s|%s" $metrics $metric -}}
                  {{- end -}}
                {{- end }}
              metric_relabel_configs:
                - source_labels: [__name__]
                  separator: ;
                  regex: {{ $metrics }}
                  replacement: $1
                  action: keep
              {{- end }}

      otlp:
        protocols:
          grpc: {}
          http: {}

    processors:
      k8sattributes:
        extract:
          metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time

          {{- with .Values.deployment.processors.receiver.k8sattributes.labels }}
          labels: {{ toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.deployment.processors.receiver.k8sattributes.annotations }}
          annotations: {{ toYaml . | nindent 12 }}
          {{- end }}

        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection

      attributes:
        actions:
          - key: k8s.cluster.name
            value: {{ .Values.clusterName }}
            action: upsert

      attributes/self:
        actions:
          - key: otelcollector.type
            value: deployment-receiver
            action: upsert
          - key: k8s.node.name
            value: $MY_NODE_NAME
            action: upsert
          - key: k8s.namespace.name
            value: $MY_NAMESPACE_NAME
            action: upsert
          - key: k8s.pod.name
            value: $MY_POD_NAME
            action: upsert

      {{- range $teamName, $teamInfo := $teams }}
        {{- if and (ne $teamInfo.ignore true) (ne (len $teamInfo.namespaces) 0) }}
      filter/{{ $teamName }}:
        error_mode: ignore
        metrics:
          datapoint:
            - {{ $teamInfo.filter }}
        logs:
          log_record:
            - {{ $teamInfo.filter }}
        {{- end }}
      {{- end }}

      memory_limiter:
         check_interval: 1s
         limit_percentage: 80
         spike_limit_percentage: 25

      batch:
        send_batch_max_size: 1000
        timeout: 30s
        send_batch_size : 800

    exporters:
      loadbalancing:
        protocol:
          otlp:
            tls:
              insecure: true
        resolver:
          dns:
            hostname: "{{ include "nrotel.headlessServiceNameSampler" . }}"

      {{- range $teamName, $teamInfo := $teams }}
        {{- if ne $teamInfo.ignore true }}
      otlphttp/{{ $teamName }}:
        endpoint: ${{ $teamName }}_endpoint
        tls:
          insecure: false
        headers:
          api-key: ${{ $teamName }}_licenseKey
        {{- end }}
      {{- end }}

      logging:
        verbosity: detailed

    extensions:
      memory_ballast:
        size_in_percentage: {{ .Values.deployment.extensions.memory_ballast.receiver.size_in_percentage }}

    service:
      extensions:
        - memory_ballast

      pipelines:
        metrics/self:
          receivers:
            - prometheus/self
          processors:
            - memory_limiter
            - k8sattributes
            - attributes
            - attributes/self
            - batch
          exporters:
            - otlphttp/opsteam
            # - logging

        {{- range $teamName, $teamInfo := $teams }}
          {{- if ne $teamInfo.ignore true }}
        metrics/{{ $teamName }}:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - k8sattributes
            - attributes
          {{- if ne (len $teamInfo.namespaces) 0 }}
            - filter/{{ $teamName }}
          {{- end }}
            - batch
          exporters:
            - otlphttp/{{ $teamName }}
            # - logging
          {{- end }}
        {{- end }}

        traces:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - k8sattributes
            - attributes
            - batch
          exporters:
            - loadbalancing
            # - logging

        {{- range $teamName, $teamInfo := $teams }}
          {{- if ne $teamInfo.ignore true }}
        logs/{{ $teamName }}:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - k8sattributes
            - attributes
          {{- if ne (len $teamInfo.namespaces) 0 }}
            - filter/{{ $teamName }}
          {{- end }}
            - batch
          exporters:
            - otlphttp/{{ $teamName }}
            # - logging
          {{- end }}
        {{- end }}

      telemetry:
        # logs:
        #   level: DEBUG
        metrics:
          address: 127.0.0.1:{{ .Values.deployment.ports.prometheus.targetPort }}
{{- end -}}
