{{- if eq .Values.singleton.enabled true -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nrotel.singletonName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.singleton.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.statefulset.serviceAccount.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end -}}
