{{- if eq .Values.singleton.enabled true -}}
{{- $teams := include "statefulsetTeamConfig" . | fromYaml }}
  {{- range $teamName, $teamInfo := $teams }}
    {{- if ne $teamInfo.ignore true -}}
      {{- if and (not $teamInfo.licenseKey.secretRef) $teamInfo.licenseKey.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nrotel.singletonName" $ }}-{{ $teamName }}
  namespace: {{ $.Release.Namespace }}
data:
  licenseKey: {{ $teamInfo.licenseKey.value | b64enc }}
---
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
